# Python for Finance, Part I: Yahoo & Google Finance API, pandas, and matplotlib  

https://www.learndatasci.com/tutorials/python-finance-part-yahoo-finance-api-pandas-matplotlib/

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from pandas_datareader import data

In [15]:
# Defunen the instruments to download. We Would like to see Apple, Microsoft and the S&P500 index
tickers = ['AAPL', 'MSFT', '^GSPC']

# We would like all available data form 01/01/2000 until 12/31/2016
start_date = '2010-01-01'
end_date = '2016-12-31'

# Use pandas_reader.data.Datareader to load the desired data
# panel_data = data.DataReader('INPX', data_source='yahoo', start=start_date, end=end_date)
panel_data = yf.download(tickers=tickers, start=start_date, end=end_date)

[*********************100%***********************]  3 of 3 completed

In [16]:
type(panel_data)

pandas.core.frame.DataFrame

In [20]:
panel_data.head(20)

           Adj Close                             Close             \
                AAPL       MSFT        ^GSPC      AAPL       MSFT
Date
2010-01-04  6.572422  23.994564  1132.989990  7.643214  30.950001
2010-01-05  6.583784  24.002319  1136.520020  7.656429  30.959999
2010-01-06  6.479061  23.855013  1137.140015  7.534643  30.770000
2010-01-07  6.467082  23.606922  1141.689941  7.520714  30.450001
2010-01-08  6.510078  23.769743  1144.979980  7.570714  30.660000
2010-01-11  6.452650  23.467388  1146.979980  7.503929  30.270000
2010-01-12  6.379251  23.312330  1136.219971  7.418571  30.070000
2010-01-13  6.469232  23.529409  1145.680054  7.523214  30.350000
2010-01-14  6.431766  24.002319  1148.459961  7.479643  30.959999
2010-01-15  6.324279  23.924789  1136.030029  7.354643  30.860001
2010-01-19  6.604054  24.110857  1150.229980  7.680000  31.100000
2010-01-20  6.502402  23.715466  1138.040039  7.561786  30.590000
2010-01-21  6.389999  23.265818  1116.479980  7.431071  30.010000
2010-01-22  6.073064  22.451782  1091.760010  7.062500  28.959999
2010-01-25  6.236445  22.730886  1096.780029  7.252500  29.320000
2010-01-26  6.324587  22.870424  1092.170044  7.355000  29.500000
2010-01-27  6.384165  23.002224  1097.500000  7.424286  29.670000
2010-01-28  6.120359  22.606833  1084.530029  7.117500  29.160000
2010-01-29  5.898319  21.847075  1073.869995  6.859286  28.180000
2010-02-01  5.980317  22.025387  1089.189941  6.954643  28.410000

                             High                               Low  \
                  ^GSPC      AAPL       MSFT        ^GSPC      AAPL
Date
2010-01-04  1132.989990  7.660714  31.100000  1133.869995  7.585000
2010-01-05  1136.520020  7.699643  31.100000  1136.630005  7.616071
2010-01-06  1137.140015  7.686786  31.080000  1139.189941  7.526786
2010-01-07  1141.689941  7.571429  30.700001  1142.459961  7.466071
2010-01-08  1144.979980  7.571429  30.879999  1145.390015  7.466429
2010-01-11  1146.979980  7.607143  30.760000  1149.739990  7.444643
2010-01-12  1136.219971  7.491786  30.400000  1143.810059  7.372143
2010-01-13  1145.680054  7.533214  30.520000  1148.400024  7.289286
2010-01-14  1148.459961  7.516429  31.100000  1150.410034  7.465000
2010-01-15  1136.030029  7.557143  31.240000  1147.770020  7.352500
2010-01-19  1150.229980  7.685357  31.240000  1150.449951  7.401429
2010-01-20  1138.040039  7.698214  30.940001  1147.949951  7.482143
2010-01-21  1116.479980  7.618214  30.719999  1141.579956  7.400357
2010-01-22  1091.760010  7.410714  30.200001  1115.489990  7.041429
2010-01-25  1096.780029  7.310714  29.660000  1102.969971  7.149643
2010-01-26  1092.170044  7.632500  29.850000  1103.689941  7.235000
2010-01-27  1097.500000  7.520714  29.820000  1099.510010  7.126071
2010-01-28  1084.530029  7.339286  29.870001  1100.219971  7.096429
2010-01-29  1073.869995  7.221429  29.920000  1096.449951  6.794643
2010-02-01  1089.189941  7.000000  28.480000  1089.380005  6.832143

                                        Open                          \
                 MSFT        ^GSPC      AAPL       MSFT        ^GSPC
Date
2010-01-04  30.590000  1116.560059  7.622500  30.620001  1116.560059
2010-01-05  30.639999  1129.660034  7.664286  30.850000  1132.660034
2010-01-06  30.520000  1133.949951  7.656429  30.879999  1135.709961
2010-01-07  30.190001  1131.319946  7.562500  30.629999  1136.270020
2010-01-08  30.240000  1136.219971  7.510714  30.280001  1140.520020
2010-01-11  30.120001  1142.020020  7.600000  30.709999  1145.959961
2010-01-12  29.910000  1131.770020  7.471071  30.150000  1143.810059
2010-01-13  30.010000  1133.180054  7.423929  30.260000  1137.310059
2010-01-14  30.260000  1143.800049  7.503929  30.309999  1145.680054
2010-01-15  30.709999  1131.390015  7.533214  31.080000  1147.719971
2010-01-19  30.680000  1135.770020  7.440357  30.750000  1136.030029
2010-01-20  30.309999  1129.250000  7.675357  30.809999  1147.949951
2010-01-21  30.000000  1114.839966  7.574286  30.610001  1138.680054
2010-01-22  28.840000  1090.180054  7.385000  30.000000  1115.489990
2010-01-25  29.100000  1092.400024  7.232500  29.240000  1092.400024
2010-01-26  29.090000  1089.859985  7.355357  29.200001  1095.800049
2010-01-27  29.020000  1083.109985  7.387500  29.350000  1091.939941
2010-01-28  28.889999  1078.459961  7.318929  29.840000  1096.930054
2010-01-29  27.660000  1071.589966  7.181429  29.900000  1087.609985
2010-02-01  27.920000  1073.890015  6.870357  28.389999  1073.890015

                Volume
                  AAPL       MSFT       ^GSPC
Date
2010-01-04   493729600   38409100  3991400000
2010-01-05   601904800   49749600  2491020000
2010-01-06   552160000   58182400  4972660000
2010-01-07   477131200   50559700  5270680000
2010-01-08   447610800   51197400  4389590000
2010-01-11   462229600   68754700  4255780000
2010-01-12   594459600   65912100  4716160000
2010-01-13   605892000   51863500  4170360000
2010-01-14   432894000   63228100  3915200000
2010-01-15   594067600   79913200  4758730000
2010-01-19   730007600   46575700  4724830000
2010-01-20   612152800   54849500  4810560000
2010-01-21   608154400   73086700  6874290000
2010-01-22   881767600  102004600  6208650000
2010-01-25  1065699600   63373000  4481390000
2010-01-26  1867110000   66639900  4731910000
2010-01-27  1722568400   63949500  5319120000
2010-01-28  1173502400  117513700  5452400000
2010-01-29  1245952400  193888500  5412850000
2010-02-01   749876400   85931100  4077610000

In [19]:
panel_data['Close']['AAPL']

Date
2010-01-04     7.643214
2010-01-05     7.656429
2010-01-06     7.534643
2010-01-07     7.520714
2010-01-08     7.570714
                ...
2016-12-23    29.129999
2016-12-27    29.315001
2016-12-28    29.190001
2016-12-29    29.182501
2016-12-30    28.955000
Name: AAPL, Length: 1762, dtype: float64

In [23]:
# Getting 
close = panel_data['Close'].copy()

In [24]:
close

                 AAPL       MSFT        ^GSPC
Date
2010-01-04   7.643214  30.950001  1132.989990
2010-01-05   7.656429  30.959999  1136.520020
2010-01-06   7.534643  30.770000  1137.140015
2010-01-07   7.520714  30.450001  1141.689941
2010-01-08   7.570714  30.660000  1144.979980
...               ...        ...          ...
2016-12-23  29.129999  63.240002  2263.790039
2016-12-27  29.315001  63.279999  2268.879883
2016-12-28  29.190001  62.990002  2249.919922
2016-12-29  29.182501  62.900002  2249.260010
2016-12-30  28.955000  62.139999  2238.830078

[1762 rows x 3 columns]